export {
  Root,
  Trigger,
  Portal,
  Overlay,
  Content,
  Title,
  Description,
  Action,
  Cancel,
  alertDialogOverlayVariants,
  alertDialogContentVariants,
  alertDialogTitleVariants,
  alertDialogDescriptionVariants,
  type AlertDialogProps,
  type AlertDialogTriggerProps,
  type AlertDialogPortalProps,
  type AlertDialogOverlayProps,
  type AlertDialogContentProps,
  type AlertDialogTitleProps,
  type AlertDialogDescriptionProps,
  type AlertDialogActionProps,
  type AlertDialogCancelProps,
  type AlertDialogOverlayVariantProps,
  type AlertDialogContentVariantProps,
  type AlertDialogContentSize,
  type AlertDialogTriggerElement,
  type AlertDialogOverlayElement,
  type AlertDialogContentElement,
  type AlertDialogTitleElement,
  type AlertDialogDescriptionElement,
  type AlertDialogActionElement,
  type AlertDialogCancelElement,
} from "./AlertDialog";

/** Unchanged Radix surface — behavior/API identical to `@radix-ui/react-alert-dialog`. */
export { createAlertDialogScope } from "@radix-ui/react-alert-dialog";
