export {
  Root,
  Trigger,
  Value,
  Icon,
  Portal,
  Content,
  Viewport,
  Item,
  ItemText,
  ItemIndicator,
  Group,
  Label,
  Separator,
  ScrollUpButton,
  ScrollDownButton,
  Arrow,
  selectTriggerVariants,
  selectIconVariants,
  selectContentVariants,
  selectViewportVariants,
  selectItemVariants,
  selectItemIndicatorVariants,
  selectLabelVariants,
  selectSeparatorVariants,
  selectScrollButtonVariants,
  selectArrowVariants,
  type SelectProps,
  type SelectTriggerProps,
  type SelectValueProps,
  type SelectIconProps,
  type SelectPortalProps,
  type SelectContentProps,
  type SelectViewportProps,
  type SelectItemProps,
  type SelectItemTextProps,
  type SelectItemIndicatorProps,
  type SelectGroupProps,
  type SelectLabelProps,
  type SelectSeparatorProps,
  type SelectScrollUpButtonProps,
  type SelectScrollDownButtonProps,
  type SelectArrowProps,
  type SelectTriggerVariantProps,
  type SelectTriggerColor,
  type SelectTriggerSize,
  type SelectContentVariantProps,
  type SelectItemVariantProps,
  type SelectTriggerElement,
  type SelectValueElement,
  type SelectIconElement,
  type SelectContentElement,
  type SelectViewportElement,
  type SelectItemElement,
  type SelectItemTextElement,
  type SelectItemIndicatorElement,
  type SelectGroupElement,
  type SelectLabelElement,
  type SelectSeparatorElement,
  type SelectScrollUpButtonElement,
  type SelectScrollDownButtonElement,
  type SelectArrowElement,
} from "./Select";

/** Unchanged Radix surface — behavior/API identical to `@radix-ui/react-select`. */
export {
  createSelectScope,
  unstable_BubbleInput,
  unstable_Provider,
  unstable_SelectBubbleInput,
  unstable_SelectProvider,
} from "@radix-ui/react-select";
