export {
  Root,
  Trigger,
  Portal,
  Overlay,
  Content,
  Title,
  Description,
  Close,
  dialogOverlayVariants,
  dialogContentVariants,
  dialogTitleVariants,
  dialogDescriptionVariants,
  type DialogProps,
  type DialogTriggerProps,
  type DialogPortalProps,
  type DialogOverlayProps,
  type DialogContentProps,
  type DialogTitleProps,
  type DialogDescriptionProps,
  type DialogCloseProps,
  type DialogOverlayVariantProps,
  type DialogContentVariantProps,
  type DialogContentSize,
  type DialogTriggerElement,
  type DialogOverlayElement,
  type DialogContentElement,
  type DialogTitleElement,
  type DialogDescriptionElement,
  type DialogCloseElement,
} from "./Dialog";

/** Unchanged Radix surface — behavior/API identical to `@radix-ui/react-dialog`. */
export { createDialogScope, WarningProvider } from "@radix-ui/react-dialog";
