import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

/**
 * Vite config for Storybook only.
 *
 * Library consumption is JIT (raw TypeScript via package `exports`) — there is
 * no lib/dist build. Token CSS is generated by `scripts/generate-tokens.mts`.
 */
export default defineConfig({
  plugins: [react(), tailwindcss()],
});
