export {
  Root,
  Trigger,
  Portal,
  Content,
  Item,
  CheckboxItem,
  RadioGroup,
  RadioItem,
  Label,
  Separator,
  Group,
  ItemIndicator,
  Arrow,
  Sub,
  SubTrigger,
  SubContent,
  dropdownMenuContentVariants,
  dropdownMenuItemVariants,
  dropdownMenuLabelVariants,
  dropdownMenuSeparatorVariants,
  dropdownMenuItemIndicatorVariants,
  dropdownMenuArrowVariants,
  type DropdownMenuProps,
  type DropdownMenuTriggerProps,
  type DropdownMenuPortalProps,
  type DropdownMenuContentProps,
  type DropdownMenuItemProps,
  type DropdownMenuCheckboxItemProps,
  type DropdownMenuRadioGroupProps,
  type DropdownMenuRadioItemProps,
  type DropdownMenuLabelProps,
  type DropdownMenuSeparatorProps,
  type DropdownMenuGroupProps,
  type DropdownMenuItemIndicatorProps,
  type DropdownMenuArrowProps,
  type DropdownMenuSubProps,
  type DropdownMenuSubTriggerProps,
  type DropdownMenuSubContentProps,
  type DropdownMenuContentVariantProps,
  type DropdownMenuItemVariantProps,
  type DropdownMenuItemTone,
  type DropdownMenuTriggerElement,
  type DropdownMenuContentElement,
  type DropdownMenuItemElement,
  type DropdownMenuCheckboxItemElement,
  type DropdownMenuRadioItemElement,
  type DropdownMenuLabelElement,
  type DropdownMenuSeparatorElement,
  type DropdownMenuGroupElement,
  type DropdownMenuItemIndicatorElement,
  type DropdownMenuArrowElement,
  type DropdownMenuSubTriggerElement,
  type DropdownMenuSubContentElement,
} from "./DropdownMenu";

/** Unchanged Radix surface — behavior/API identical to `@radix-ui/react-dropdown-menu`. */
export { createDropdownMenuScope } from "@radix-ui/react-dropdown-menu";
